language: node_js
node_js: "10"
cache: yarn

install: (cd functions && yarn)
before_script:
  - |
    echo -e "export const BOT = {
      token: '',
      apiPrefix: '',
      chatId: '',
    };" > functions/local.ts
script: (cd functions && yarn build)

notifications:
  webhooks: https://us-central1-hook-a4883.cloudfunctions.net/travisTelegram
