language: node_js
node_js: "10"
cache: yarn

install: (cd functions && yarn)
before_script:
  - |
    echo -e "export const BOT = {
      token: '',
      apiPrefix: '',
      chatId: '',
    };" > functions/src/local.ts
  - cat functions/src/local.ts
script: (cd functions && yarn build)

notifications:
  # replace with your own webhook
  webhooks: https://us-central1-hook-a4883.cloudfunctions.net/travisTelegram
